server:
  port: 8083
spring:
  spring:
    data:
      rest:
        basePath=/:
  datasource:
    initialization-mode: always
  h2:
    console:
      enabled: true
      path: /h2
  jpa:
    properties:
      hibernate.dialect: org.hibernate.dialect.H2Dialect
    database: h2
    hibernate:
      ddl-auto: create-drop
    show_sql: true
  main:
    banner-mode: "off"
