insert into providers (name, km) Values ('Форов', 47);
insert into providers (name, km) Values ('Дьяков', 15);
insert into providers (name, km) Values ('Рубежное', 33);
insert into providers (name, km) Values ('УМ_Салтов', 12);
insert into providers (name, km) Values ('Маяк', 8);
insert into type_of_raw_materials (name) Values ('Твердая');
insert into type_of_raw_materials (name) Values ('Мягкая');
insert into type_of_raw_materials (name) Values ('Сосна');
insert into type_of_raw_materials (name) Values ('Микс');
insert into kind_of_raw_materials (name) Values ('Обзел');
insert into kind_of_raw_materials (name) Values ('Тырса');
insert into kind_of_raw_materials (name) Values ('Дрова');
insert into kind_of_raw_materials (name) Values ('Щепа');
